[package]
name = "p2p2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
runtime-smol = ["agnostik/runtime_smol"]
runtime-tokio = ["agnostik/runtime_tokio"]
runtime-asyncstd = ["agnostik/runtime_asyncstd"]
runtime-bastion = ["agnostik/runtime_bastion"]


tcp = []
udp = []

[dependencies]
agnostik = {version = "0.2.3", features=[]}
serde = {version="1.0.130", features=["derive"]}
thiserror = "1.0.29"
bincode = "1.3.3"
sodiumoxide = "0.2.7"
rand = "0.8.4"